### PR TITLE
Add pull to refresh to artists and auctions

### PR DESCRIPTION
**Pull request by alloy**
Related to https://github.com/artsy/collector-experience/issues/855

This only adds pull-to-refresh to these views, rather than a more comprehensive data invalidation scheme, but that can probably wait till post v4.0.0.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  [danger-plugin-jest] Could not read test results. Danger cannot pass or fail the build.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by alloy** [comment]
Whomever wants to review/merge can take it.

**Comment by orta** [comment]
Works for me, looks good 👍

**Comment by mzikherman** [comment]
👍

**Pull request merged**
