### PR TITLE
TypeScript and React Native upgrade

### PR DESCRIPTION
**Pull request by alloy**
Supersedes #437 and #438.

- [x] The packager still doesn’t appear to pick up the TS files, rather it reads from `./build`.
- [x] ~~Add types to remaining classes.~~ I suppose this was meant to be about fixing all type errors?
- [x] Make CI green.
- [x] Fix hot-reloading.
- [x] Fix TS->JS source-maps.
- [ ] Fix disabled Gene view snapshot test.
- [ ] Look into FlatList replacement for ListView on Home view.

### CODE REVIEW

**Comment by alloy** [comment]
@l2succes @sarahscott Can you give this a spin and see if it functions similarly well to the existing TS branch? If so, then we can go ahead and close those other 2 Hrs in favour of this one.

**Comment by orta** [comment]
look at all those co-commits, this guy really knows how to use git correctly 🍡

**Comment by orta** [comment]
The build references come directly from `index.ios.js`
```
import Containers from './build/lib/containers'
import Components from './build/lib/components'
import Routes from './build/lib/relay/routes'

import './build/lib/relay/config'
import './build/lib/app_registry'

export default {
  Containers,
  Components,
  Routes,
}
```

**Comment by orta** [comment]
Yep: 

screen shot 2017-02-24 at 08 43 51

**Comment by orta** [comment]
Tests pass locally, re-running travis without cache

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by alloy** [comment]
> The build references come directly from `index.ios.js`

Doh, hahaha. Thanks for the catch 👌

**Comment by alloy** [comment]
The build is red because of other things than tests. I’ll see if I can make some progress there.

**Comment by alloy** [comment]
So all TS build errors are now fixed, but the build remains red because for some reason jest is not picking up any tests, eslint is failing to run, and danger is complaining about some validation.

```
$ yarn run lint
yarn run v0.20.3
$ eslint ./lib ./test 
sh: 1: eslint: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run lint" exited with 1.

$ yarn run danger
yarn run v0.20.3
$ danger 
OK, looks good Travis CI on GitHub
Found some validation failure
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run danger" exited with 1.
```

**Comment by orta** [comment]
screen shot 2017-02-27 at 08 48 52
Theres the message for Danger ^

That lint error is because aslant was removed, re: JEst - probably test paths needs updating? I think the config name may have changed in jest 19

**Comment by alloy** [comment]
> Theres the message for Danger ^

Aha. I didn’t link that from the general message on CI :)

> That lint error is because aslant was removed

Ooohhhh, I see. Apparently the task still runs fine on my machine because I installed eslint globally at some point and `yarn run command` does not isolate.

> re: JEst - probably test paths needs updating? I think the config name may have changed in jest 19

But `yarn test` runs fine locally 🤔

**Comment by alloy** [comment]
Alright, let’s get this in!

**Comment by alloy** [comment]
Ok, so there’s a couple of red screens that show during development when navigating back and forth. This is really annoying and requires a lot of reloading, however these problems do not manifest when building a release bundle.

So I say we :shipit: now and I’ll look into fixing the annoying dev bugs afterwards.

**Comment by l2succes** [comment]
@alloy I double-checked all the views, I'm not sure if you noticed but the Gene refining page appears blank on initial load. You have to start scrolling for artworks to show. It only happens the first time though, after the data loads once it works fine.  Not sure if that's a real issue or not, if it is maybe we can tackle the bug in a separate PR.

Aside from that and the keyboard everything else looks good. If the issue mentioned above isn't a problem let's merge it.

Before scrolling:
simulator screen shot mar 7 2017 3 16 32 pm

After scrolling:
simulator screen shot mar 7 2017 3 20 02 pm

**Comment by alloy** [comment]
Good catch! That's definitely not supposed to happen, but I'm working on gene refining this week anyways, so I can PR that fix separately 👍

**Comment by orta** [comment]
Congrats 🎉

**Pull request merged**
