### PR TITLE
[MSG] Zero state for Inbox

### LINKED ISSUE #591: [MSG] Add Inbox container zero state
Relates to [this ticket on CE](https://github.com/artsy/collector-experience/issues/295)
Assets are in [Zeplin](https://app.zeplin.io/project/5926ec3efb21cc40615158cc/screen/5935c5359dd9f22d3ee63ab1)

screen shot 2017-06-07 at 11 01 17

### PR DESCRIPTION
**Pull request by mennenia**
That one time Inbox Zero is not so desirable, and we want you to inquire on artwork! 😄 

Fix #591 

Implementation:
screen shot 2017-06-07 at 11 01 17

Spec:
screen shot 2017-06-07 at 11 01 17

Unfortunately the text is a bit smaller than the design asks for, but then the 3rd paragraph ends up on 3 lines :(. Also the status bar 😅...

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  No CHANGELOG added.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Missing Test Files:

- `src/lib/components/inbox/conversations/__tests__/zerostateinbox-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "Skip New Tests".
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
Awesome - this looks like a perfect example for my jest-svg-snapshots! If #587 gets in before this, you should add one of those tests

**Comment by mennenia** [comment]
@orta I don't understand what this build is failing on... from what I gather, it's having issues running prettier?

**Comment by alloy** [comment]
Afaik prettier runs on CI as a linter, which means it expects there to not be anything to prettify anymore. If this is the case, the output of prettier is very unhelpful, though.

**Comment by mennenia** [comment]
So when I lint locally, everything seems to pass and there are no changes introduced. I'm using `yarn lint`, nothing specific to prettier. Should I be using a different command?

**Comment by orta** [comment]
Yeah, agreed on the output, it should be listing all the files that it thinks aren't the same as the format - but from here it looks like it's listing every file in our repo

**Comment by alloy** [comment]
The command [used on CI](https://github.com/artsy/emission/blob/08e1a478d676a27167d1729b0385aa4fb6b47bb5/package.json#L17) is `yarn prettier-project -- -l`

**Comment by orta** [comment]
IMO we're hitting a prettier bug, my guess is that `-l` isn't taking `ENV["CI"]` into account and so shows both "passing" and "failing"

**Comment by mennenia** [comment]
Kk that was the final push of code / test fixing :). Hopefully this goes green and then it's good to PR @orta

**Comment by orta** [comment]
👍

**Pull request merged**
