### PR TITLE
Adds recently viewed works rail

### PR DESCRIPTION
**Pull request by sarahscott**
Adds the new Recently Viewed Works rail to emission 🎨

Part of: https://artsyproduct.atlassian.net/browse/DISCOVER-66

simulator screen shot - iphone 8 plus - 2018-04-26 at 11 51 50

(not sure why some of these images aren't loading in the simulator but it's not specific to this rail)

#skip_new_tests because this is just adding a field to a graphQL query; no UI/functionality changes

### CODE REVIEW

**Comment by mennenia** [comment]
@sarahscott are the images loading on device?

**Comment by sarahscott** [comment]
I can check! FWIW the image loading issue is happening on master for me in the sim as well.

**Comment by sarahscott** [comment]
It could just be my computer

**Comment by sarahscott** [comment]
Randomly, in other rails as well.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Missing Test Files:

- `src/lib/Scenes/Home/Components/ForYou/__tests__/index-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by mennenia** [comment]
Works fine on device, merging 👍

**Pull request merged**
