### PR TITLE
Automated release

### PR DESCRIPTION
**Pull request by alloy**
Going to self-merge, just a heads up.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Changes were made to package.json, but not to yarn.lock - <i>Perhaps you need to run `yarn install`?</i></td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
Nice one on automating all that process

**Comment by alloy** [comment]
Now to see if it actually works :D

**Comment by alloy** [comment]
Had to make one fix, but otherwise worked like a charm:

```
~/C/A/emission [master] » npm version patch
v1.3.6

> emission@1.3.6 version /Users/eloy/Code/Artsy/emission
> yarn install && yarn bundle && pushd Example && pod install && popd && git add Pod/Assets Example/Podfile.lock

yarn install v0.23.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.15s.
yarn bundle v0.23.4
$ react-native bundle --config rn-cli.config.js --platform=ios --dev=false --entry-file=index.ios.js --bundle-output Pod/Assets/Emission.js --sourcemap-output Pod/Assets/Emission.js.map --assets-dest Pod/Assets && rm -r Pod/Assets/assets/node_modules 
Scanning 962 folders for symlinks in /Users/eloy/Code/Artsy/emission/node_modules (10ms)
Scanning 962 folders for symlinks in /Users/eloy/Code/Artsy/emission/node_modules (15ms)
Loading dependency graph...watchman warning:  Recrawled this watch 1 times, most recently because:
/Users/eloy/Code/Artsy/emission: kFSEventStreamEventFlagKernelDropped
To resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del /Users/eloy/Code/Artsy/emission ; watchman watch-project /Users/eloy/Code/Artsy/emission`

Loading dependency graph, done.
bundle: start
bundle: finish
bundle: Writing bundle output to: Pod/Assets/Emission.js
bundle: Writing sourcemap output to: Pod/Assets/Emission.js.map
bundle: Done writing bundle output
bundle: Done writing sourcemap output
bundle: Copying 17 asset files
bundle: Done copying assets
✨  Done in 20.81s.
~/Code/Artsy/emission/Example ~/Code/Artsy/emission
Analyzing dependencies
Fetching podspec for `Emission` from `../`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `SentryReactNative` from `../node_modules/react-native-sentry`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Using ARGenericTableViewController (1.0.2)
Using AppHub (0.5.1)
Using Artsy+Authentication (1.5.0)
Using Artsy+UIColors (3.1.0)
Using Artsy+UIFonts (3.1.1)
Using Artsy-UIButtons (2.1.0)
Using Emission (1.3.6)
Using Extraction (1.2.3)
Using FLKAutoLayout (1.0.0)
Using ISO8601DateFormatter (0.8)
Using KSCrash (1.15.8)
Using NSURL+QueryDictionary (1.2.0)
Using ORStackView (2.0.3)
Using RSSwizzle (0.1.0)
Using React (0.42.0)
Using SAMKeychain (1.5.0)
Using SDWebImage (3.7.5)
Using Sentry (2.1.9)
Using SentryReactNative (0.8.3)
Using Specta (1.0.5)
Using UIView+BooleanAnimations (1.0.2)
Using Yoga (0.42.0.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 12 dependencies from the Podfile and 22 total pods installed.
~/Code/Artsy/emission

> emission@1.3.6 postversion /Users/eloy/Code/Artsy/emission
> git push --follow-tags && env EMISSION_ROOT="$(pwd)" pod repo push artsy --allow-warnings --use-json --skip-import-validation

Found '/Users/eloy/Code/Artsy/emission/.nvmrc' with version <6.9>
Now using node v6.9.5 (npm v3.10.10)
Found '/Users/eloy/Code/Artsy/emission/.nvmrc' with version <6.9>
Now using node v6.9.5 (npm v3.10.10)

> husky - npm run -s prepush

yarn run v0.23.4
$ tsc --noEmit --pretty 
✨  Done in 4.81s.
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 7.45 KiB | 0 bytes/s, done.
Total 15 (delta 10), reused 0 (delta 0)
remote: Resolving deltas: 100% (10/10), completed with 7 local objects.
To https://github.com/artsy/emission.git
   2f579e93..2c0981b3  master -> master
 * [new tag]           v1.3.6 -> v1.3.6

Validating spec
 -> Emission (1.3.6)
    - WARN  | xcodebuild:  Artsy-UIButtons/Pod/Classes/ARButtonSubclasses.m:44:1: warning: method possibly missing a [super awakeFromNib] call [-Wobjc-missing-super-calls]
    - WARN  | xcodebuild:  ORStackView/Classes/ios/ORSplitStackView.m:36:11: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    - WARN  | xcodebuild:  ORStackView/Classes/ios/ORSplitStackView.m:37:18: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    - WARN  | xcodebuild:  ORStackView/Classes/ios/ORSplitStackView.m:39:11: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    - WARN  | xcodebuild:  ORStackView/Classes/ios/ORSplitStackView.m:40:11: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    - WARN  | xcodebuild:  ORStackView/Classes/ios/ORStackView.m:41:1: warning: method possibly missing a [super awakeFromNib] call [-Wobjc-missing-super-calls]
    - WARN  | xcodebuild:  ORStackView/Classes/ios/ORStackView.m:168:15: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    - WARN  | xcodebuild:  React/React/Base/RCTBatchedBridge.m:737:6: warning: code will never be executed [-Wunreachable-code]
    - WARN  | xcodebuild:  React/React/Base/RCTBatchedBridge.m:813:14: warning: unused variable 'length' [-Wunused-variable]
    - WARN  | [iOS] xcodebuild:  React/React/Base/RCTConvert.m:344:1: warning: implicit conversion loses integer precision: 'unsigned long long' to 'UIDataDetectorTypes' (aka 'enum UIDataDetectorTypes') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  React/React/Base/RCTLog.mm:188:29: warning: unused function 'nativeStackFrameRegex' [-Wunused-function]
    - WARN  | xcodebuild:  React/React/Views/RCTModalHostView.m:59:24: warning: 'setFrame:forView:' is deprecated: Use `setSize:forView:` or `setIntrinsicContentSize:forView:` instead. [-Wdeprecated-declarations]
    - NOTE  | xcodebuild:  React/React/Modules/RCTUIManager.h:149:1: note: 'setFrame:forView:' has been explicitly marked deprecated here
    - WARN  | xcodebuild:  React/React/Base/RCTRootView.m:414:24: warning: 'setFrame:forView:' is deprecated: Use `setSize:forView:` or `setIntrinsicContentSize:forView:` instead. [-Wdeprecated-declarations]
    - WARN  | xcodebuild:  React/React/Modules/RCTUIManager.m:239:28: warning: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
    - NOTE  | xcodebuild:  React/React/Base/RCTEventDispatcher.h:83:1: note: 'sendDeviceEventWithName:body:' has been explicitly marked deprecated here
    - WARN  | xcodebuild:  React/React/Modules/RCTUIManager.m:387:11: warning: unused variable 'existingView' [-Wunused-variable]
    - WARN  | xcodebuild:  Sentry/Sources/BreadcrumbStore.swift:32:61: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/BreadcrumbStore.swift:32:68: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/BreadcrumbStore.swift:32:68: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/BreadcrumbStore.swift:32:75: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/BreadcrumbStore.swift:32:82: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/BreadcrumbStore.swift:32:82: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/Functions.swift:32:22: warning: bridging 'NSNumber' to 'Bool' may fail at runtime and will become a checked cast in Swift 4; did you mean to use 'as!' to force downcast?
    - WARN  | xcodebuild:  Sentry/Sources/KSCrashHandler.swift:91:38: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/KSCrashHandler.swift:91:56: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/KSCrashHandler.swift:91:56: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/RequestOperation.swift:31:44: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/RequestOperation.swift:31:45: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/RequestOperation.swift:31:45: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/Sentry+Error.swift:19:58: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/Sentry+Error.swift:19:65: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/Sentry+Error.swift:19:65: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/SentryEndpoint.swift:98:40: warning: bridging 'NSNumber' to 'Int' may fail at runtime and will become a checked cast in Swift 4; did you mean to use 'as!' to force downcast?
    - WARN  | xcodebuild:  Sentry/Sources/Thread.swift:96:40: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:41: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:41: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/Thread.swift:96:63: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:64: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:64: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/Thread.swift:96:83: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:84: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:84: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/Thread.swift:96:102: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:103: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:103: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  Sentry/Sources/Thread.swift:96:127: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:128: note: use 'String(describing:)' to silence this warning
    - NOTE  | xcodebuild:  Sentry/Sources/Thread.swift:96:128: note: provide a default value to avoid this warning
    - WARN  | xcodebuild:  SentryReactNative/ios/RNSentry.m:27:5: warning: expression result unused [-Wunused-value]
    - WARN  | xcodebuild:  SentryReactNative/ios/RNSentry.m:108:86: warning: undeclared selector 'callNativeModule:method:params:' [-Wundeclared-selector]
    - WARN  | xcodebuild:  SentryReactNative/ios/RNSentry.m:108:15: warning: incompatible pointer to integer conversion initializing 'uintptr_t' (aka 'unsigned long') with an expression of type 'IMP' (aka 'void (*)(void)') [-Wint-conversion]
    - WARN  | xcodebuild:  SentryReactNative/ios/RNSentry.m:111:30: warning: undeclared selector 'callNativeModule:method:params:' [-Wundeclared-selector]

Updating the `artsy' repo

Already up-to-date.

Adding the spec to the `artsy' repo

 - [Update] Emission (1.3.6)

Pushing the `artsy' repo

To https://github.com/artsy/Specs.git
   1b23fa6..03eaeb8  master -> master
```

**Comment by orta** [comment]
Not bad - I'm still manipulating the CocoaPods Mac app release task ;)

**Pull request merged**
