### PR TITLE
[WIP] [tsc] Enable noImplicitAny

### PR DESCRIPTION
**Pull request by alloy**
Got to a part where I got stuck because of styled-components/Palette, for which I then [started an upgrade](https://github.com/artsy/palette/pull/498) but also hit a wall. Perhaps that can be avoided altogether, which I will take a stab at next time.

### CODE REVIEW

**Comment by damassi** [comment]
@alloy - now that the upgrade is in can this work continue?

**Comment by alloy** [comment]
Unsure what upgrade you mean, but if you’re interested in continuing on this then by all means please do!

**Comment by damassi** [comment]
@alloy meaning 

> Got to a part where I got stuck because of styled-components/Palette, for which I then started an upgrade but also hit a wall.

Now that we're using the latest styled-components and palette was wondering if things might be unstuck.

**Comment by alloy** [comment]
Ah I see, didn’t know that happened. Yeah I’ll try to poke it again soon 👍

**Comment by ds300** [comment]
We've added a ticket to our backlog to get this done once and for all, but it will happen after merging emission into eigen so I'm going to close this and pilfer the approach in a few weeks 🙏

**Pull request closed without merging**
