### PR TITLE
[Consignments] iPad layouts

### PR DESCRIPTION
**Pull request by orta**
Adds support for a centered with a max-width version of the consignment screens on iPad. 

Also comes with update to jest-snapshots-svg which now renders text: https://github.com/orta/jest-snapshots-svg/pull/28

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  No CHANGELOG added.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by alloy** [comment]
Can you add a screenshot?

**Comment by orta** [comment]
screen shot 2017-08-24 at 09 42 03
screen shot 2017-08-24 at 09 41 45

**Comment by alloy** [comment]
Thanks!

Is that search list in the first screenshot supposed to not stick to the top of the screen?

**Comment by orta** [comment]
There are no iPad layouts designs, so I'm happy happy with either

**Comment by alloy** [comment]
Regardless of there being specific design for iPad, (naively) it seems to me that we’d want the search results to take up the full height of the available screen. Or are you saying that there is going to be a next phase where the design will be updated for iPad and for now we shouldn’t care about it?

**Comment by orta** [comment]
Then no, it's not meant to take the full size of the screen, the positioning is intentional.

screen shot 2017-08-24 at 09 50 22

**Comment by alloy** [comment]
Interesting. Do you happen to know the motivation for that decision? (link is fine)

**Comment by orta** [comment]
I don't, think those decisions were made in design reviews before I took on the project

**Comment by alloy** [comment]
Gotcha.

**Comment by sweir27** [comment]
👍 cool!

**Pull request merged**
