### PR TITLE
React Native 0.57 - rebase and merge branch

### PR DESCRIPTION
**Pull request by orta**
Already converted #1210 into a single commit, then will be re-basing that to master

### CODE REVIEW

**Comment by orta** [comment]
OK, this is ready to go!

**Comment by alloy** [comment]
@l2succes This will presumably be green and imo is good to merge, but I don’t want to hinder in any way work on the City Guide, in case any last minute changes need to get shipped. Perhaps we’re at the point where we do merge this to master and _if_ last minute changes need to be made, those should just be applied to a branch off of the current release tag and re-applied to master?

**Comment by l2succes** [comment]
👍Yes, I feel pretty comfortable merging the RN upgrade considering the current state of City Guide. If we need to push a hotfix as you said, we can do that off the current release tag.

**Comment by alloy** [comment]
Perfect 👌 

Merge on green, Peril buddy and, while you’re at it, pop that 🍾

**Comment by l2succes** [comment]
🙌🏾😭Can't believe it's finally happening 👏

**Comment by l2succes** [comment]
`continuous-integration/travis-ci/pr` is ✅ already not sure why it still shows up yellow. Merging

**Comment by alloy** [comment]
\o/

**Pull request merged**
