### PR TITLE
 Migrate to Relay Modern

### PR DESCRIPTION
**Pull request by alloy**
This depends on the WIP shown here https://github.com/alloy/relay/pull/3

- [x] Make Emission work with ‘classic’ mode. (But without custom Node ID support.)
- [ ] Make Relay compiler work with our TypeScript setup.
  - [x] Get babel-plugin-relay to pickup our `graphql` calls.
  - [x] Replace https://github.com/facebook/relay/pull/1710 in favour of a simple temp TS transform solution and a forked Relay.
  - [ ] Migrate to Babel 7 to get integrated TS support.
- [x] Migrate to Relay ‘compat’ mode.
- [x] Migrate to Relay ‘modern’ mode.
- [x] Ensure all imports are fixed after changing tsc to output ES2015 modules.
- [ ] Make Relay v1.x.x work with our `__id` global ID field.
  - [x] Actually make it work.
  - [ ] Publish a build of our fork so others can install and use the code in this branc.
  - [ ] Cleanup fork and submit upstream.
- [ ] Ensure Gene artworks filter refining works (after adding `__id` support)
- [x] Make Artist artworks pagination work
- [x] Upgrade React Native version to include https://github.com/facebook/react-native/commit/5550a25, see https://github.com/facebook/relay/pull/1889. Done with https://github.com/artsy/emission/pull/734
- [x] Make a conversation thread reload after sending a message.
- [ ] Check if we still need to force fetch data when loading a view now that caching has been reduced by default https://github.com/facebook/relay/issues/2046
- [ ] Go through all `TODO` items in the code base.
- [ ] Make sure that `__id` isn’t being stripped out and thus incompatible with Relay Modern, see e.g.  https://github.com/facebook/relay/blob/77dcb6a0b4f11be4799d59447d19903b61218ca0/packages/relay-runtime/store/RelayModernRecord.js#L90
- [x] Make storybooks work, probably by finishing metametaphysics to allow easy stubbing of data for components while still consuming data through Relay.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: TypeError

```sh
TypeError: recurseSync is not a function
    at Object.<anonymous> (/home/travis/build/artsy/emission/dangerfile.ts:11:7)
    at Runtime._execModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/build/index.js:513:13)
    at Runtime.requireModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/build/index.js:329:14)
    at /home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:96:13
    at ensureCleanDangerfile (/home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:135:3)
    at Object.<anonymous> (/home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:95:3)
    at step (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:32:23)
    at Object.next (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:13:53)
    at /home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:7:71
    at __awaiter (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:3:12)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: TypeError

```sh
TypeError: recurseSync is not a function
    at Object.<anonymous> (/home/travis/build/artsy/emission/dangerfile.ts:11:7)
    at Runtime._execModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/build/index.js:513:13)
    at Runtime.requireModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/build/index.js:329:14)
    at /home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:96:13
    at ensureCleanDangerfile (/home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:135:3)
    at Object.<anonymous> (/home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:95:3)
    at step (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:32:23)
    at Object.next (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:13:53)
    at /home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:7:71
    at __awaiter (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:3:12)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
I wonder what it is about this PR that breaks danger

**Comment by orta** [comment]
RN 0.48 has issues with node 8.4 - it's not our official emission node version - but worth a mention https://github.com/facebook/react-native/issues/15810 if anyone else has this error: `TypeError: Cannot read property 'BLOB_URI_SCHEME' of undefined`

**Comment by l2succes** [comment]
🚨 Alrighty merging! 🚨

@sarahscott @alloy We got all tests and build green (aside from the `travis-ci/pr` which is timing out but that should fix itself in master). We still some remaining tasks in this PR description that we can handle in separate PR.

**Comment by orta** [comment]
Congrats

**Comment by alloy** [comment]
SO. HAPPY! 🎉 

Giphy

**Pull request merged**
