### PR TITLE
[Readme] add setup step

### PR DESCRIPTION
**Pull request by mennenia**
There's probably a reason why it's not in there :P, but I blindly followed the readme instructions, and then had the simulator suggest that I should probably run `npm install`. Thought it might be worth putting in the instructions?

### CODE REVIEW

**Comment by alloy** [comment]
Weird, the reason it's not in there is because we check the modules in. Do you know what modules it installed?

**Comment by mennenia** [comment]
That's what I thought..

The error in the terminal was:

```
{ [Error: ENOENT: no such file or directory, lstat '/Users/mennenia/Developer/Artsy/emission/Example/node_modules/emission/data/schema.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/mennenia/Developer/Artsy/emission/Example/node_modules/emission/data/schema.json' }
```

(and I really should've taken a screenshot of the simulator)

I wasn't sure how to resolve that, but the RN prompt said to reinstall watchman and then npm install. Considering I knew that I had installed watchmen properly, I just figured I'd try `npm install`, after which it ran just fine... 

Output from `npm install`:
```
Emission-Example@0.0.1 /Users/mennenia/Developer/Artsy/emission/Example
└── emission@0.1.0

npm WARN Emission-Example@0.0.1 No repository field.
```

**Comment by alloy** [comment]
Hmm, interesting.  I would have expected 'npm start' to do an initial sync and place that file there. Can you 'rm -rf Example/node_modules/emission' and try again?

**Comment by mennenia** [comment]
I get the same problem again:

simulator screen shot 5 may 2016 13 37 32

**Comment by mennenia** [comment]
Got it. Should be running `npm install` from the top directory, not from within `Example`

**Comment by mennenia** [comment]
Yeah I realised, fixed now

**Comment by sarahscott** [comment]
🎉  lovely!

**Comment by sarahscott** [comment]
I also went through the same dance of figuring out where to run `npm start`. This is a very helpful addition.

**Pull request merged**
