### PR TITLE
[dev] Adds spell checker to Emission

### PR DESCRIPTION
**Pull request by orta**
Need to verify real Danger behaviour to see if it fits with what I'm seeing from Peril.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  New dependencies added: danger-plugin-spellcheck.
  </td>
    </tr>
  </tbody>
</table>



### Typoes for <a href="https://github.com/artsy/emission/blob/spell2/docs/vscode.md">vscode.md</a>

| Line | Typo |
| ---- | ---- |

  


<h2><a href="https://github.com/orta/danger-plugin-spellcheck#readme">danger-plugin-spellcheck</a></h2>
<p>Author: Orta Therox + Yuki Nishijima</p>
<p>Description: Spell checks any created or modified markdown files.</p>
<p>Homepage: <a href="https://github.com/orta/danger-plugin-spellcheck#readme">https://github.com/orta/danger-plugin-spellcheck#readme</a></p>

<table>
  <thead><tr><th></th><th width="100%"></th></tr></thead>
  <tr><td>Created</td><td>18 days ago</td></tr><tr><td>Last Updated</td><td>18 minutes ago</td></tr><tr><td>License</td><td>MIT</td></tr><tr><td>Maintainers</td><td>1</td></tr><tr><td>Releases</td><td>3</td></tr><tr><td>Direct Dependencies</td><td><a href='http: //npmjs.com/package/markdown-spellcheck'>markdown-spellcheck</a> and <a href='http: //npmjs.com/package/esdoc'>esdoc</a></td></tr><tr><td>Keywords</td><td>danger, danger-plugin and mdspell</td></tr>
</table>

<details>
<summary><code>README</code></summary>
# danger-plugin-spellcheck

[Build Status](https://travis-ci.org/orta/danger-plugin-spellcheck)
[npm version](https://badge.fury.io/js/danger-plugin-spellcheck)
[semantic-release](https://github.com/semantic-release/semantic-release)

> Spell checks any created or modified markdown files in a GitHub PR using [node-markdown-spellcheck](https://github.com/lukeapage/node-markdown-spellcheck).

## Usage

Install:

```sh
yarn add danger-plugin-spellcheck --dev
```

At a glance:

```js
// dangerfile.js
import spellcheck from 'danger-plugin-spellcheck'

schedule(spellcheck())
```

If you have a shared ignored word list:

```js
// dangerfile.js
import spellcheck from 'danger-plugin-spellcheck'

schedule(spellcheck({ ignore: "orta/words@ignore_words.json" }))
```

The JSON should look something like, case is ignored:

```json
{
  "ignore": ["orta", "artsy", "github"]
}
```


## Changelog

See the GitHub [release history](https://github.com/orta/danger-plugin-spellcheck/releases).

## Credits

This was created by [Orta Therox](https://twitter.com/orta) and [Yuki Nishijima](https://twitter.com/yuki24) in an amazing pairing session on cold thursday before an [Artsy Happy Hour](https://github.com/artsy/meta/blob/master/meta/happy_hour.md).

## Contributing

See [CONTRIBUTING.md](contributing.md).

</details>




  <details>
    <summary><code>yarn why danger-plugin-spellcheck</code> output</summary>
    <p><code><ul><li>Has been hoisted to "danger-plugin-spellcheck"</li><li>This module exists because it's specified in "devDependencies".</li><li>Disk size without dependencies: "88kB"</li><li>Disk size with unique dependencies: "11.17MB"</li><li>Disk size with transitive dependencies: "30.41MB"</li><li>Amount of shared dependencies: 45
    </li></ul></code></p>
  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by yuki24** [comment]
😥

**Comment by orta** [comment]
I'm actually good with this (in general) it means my problems aren't in Peril anymore, but inside danger-plugin-spellcheck 👍

**Comment by orta** [comment]
Alright, I'm going to close this, as Peril will probably handle it for here.

**Pull request closed without merging**
