### PR TITLE
[Messages] Allow blank-body messages, but filter for completely blank messages in fragment

### PR DESCRIPTION
**Pull request by sarahscott**
- [x] Adds `ignoreBlankMessages` parameter to `Messages` fragment
- [x] Renders messages with blank bodies

https://artsyproduct.atlassian.net/browse/IN-56 #resolve

We will be filtering for completely blank messages (i.e. no attachments or body) in metaphysics, but in a worst case, they look like this, which is acceptable IMO:

blank messages
 
#skip_new_tests

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Missing Test Files:

- `src/lib/Components/Inbox/Conversations/__tests__/index-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  [danger-plugin-jest] Could not read test results. Danger cannot pass or fail the build.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by alloy** [comment]
Ah ok, so validation does kick in. Ok, I’ll make a little MP PR that only adds the parameter for now.

**Comment by orta** [comment]
Lolz, @mdole got the co-sign instead of @ashkan18 - ah well

**Comment by alloy** [comment]
Nice, such team 🙆‍♂️

**Pull request merged**
