### PR TITLE
[DependencyCI] Skip deprecation check on transitive dep.

### PR DESCRIPTION
**Pull request by alloy**
Testing.

### CODE REVIEW

**Comment by andrew** [comment]
The file name might need quotes around it, will do some testing on my end too

**Comment by alloy** [comment]
That doesn’t seem to fix it either. Thus far I tried:

```yaml
platforms:
  npm:
    jade:
      tests:
        deprecated: skip
```

```yaml
files:
  npm-shrinkwrap.json:
    jade:
      tests:
        deprecated: skip
```

```yaml
files:
  "npm-shrinkwrap.json":
    jade:
      tests:
        deprecated: skip
```

**Comment by andrew** [comment]
That top one should be working, definitely a problem on my end, just looking into it now for you

```yaml
platforms:
  npm:
    jade:
      tests:
        deprecated: skip
```

**Comment by andrew** [comment]
Ah, try this: 

```yaml
platforms:
  NPM:
    jade:
      tests:
        deprecated: skip
```

Case sensitive hashes in yaml 😬

**Comment by alloy** [comment]
Alas, that also doesn’t seem to do the trick.

**Comment by andrew** [comment]
Tests passed!

**Comment by orta** [comment]
👍 niccceeee

**Comment by orta** [comment]
I want this for #215

**Pull request merged**
