### PR TITLE
[WFU] Let nested components decide what data to fetch.

### LINKED ISSUE #540: deeplink from personalized email causes crash
gif
https://cl.ly/3a3h2J0n2B3z

unfortunately I'm not being prompted for sending the crash report, here's what I managed to pull from my phone logs https://cl.ly/3K2I2w2O2b2m

### PR DESCRIPTION
**Pull request by alloy**
Fixes #540

Skip New Tests

### CODE REVIEW

**Comment by alloy** [comment]
This is not the long term fix. Once we’ve got the release out, I want to move creating the special notification to MP so that the client can just use the `Notification` fragment for all of this.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Missing Test Files:

- `src/lib/components/works_for_you/__tests__/notification-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "Skip New Tests".</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Could not find stories using these components:

- `Notification`

</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by sarahscott** [comment]
LGTM 👍

**Comment by alloy** [comment]
Ok 💚, merging

**Pull request merged**
