### PR TITLE
Moves native view controllers to use iOS7+ status bar api.

### PR DESCRIPTION
**Pull request by ashfurrow**
To accompany https://github.com/artsy/eigen/pull/2368

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by ashfurrow** [comment]
What's the process for releasing a new version of Emission? Is that something I have access to?

**Comment by orta** [comment]
I don't see any deployment docs, and I've not done it myself. Leaving that one (both in terms of _should_ it be deployed, and how) to @alloy

**Comment by alloy** [comment]
https://github.com/artsy/emission#deployment

**Comment by ashfurrow** [comment]
Okay, so the deploy didn't quite go as planned but that's okay, we got it sorted in the end. Here's a run-through of what happened:

1. I tried to deploy 1.3.7, not understanding the full scope of changes made since 1.3.6.
1. The deploy failed because the RN version update wasn't reflected in our Specs repo.
1. Orta troubleshooted with me.
1. I branched from the 1.3.6 release, cherry-picked the commit from this PR, and deployed 1.3.8.
1. Ran into some issues with the 1.3.8 deploy, did a 1.3.9 deploy.
1. Submitted https://github.com/artsy/emission/pull/619 to merge releases into master.

**Pull request merged**
