### PR TITLE
Start looking at testing

### PR DESCRIPTION
**Pull request by orta**
- [x] Danger
- [x] Travis
- [x] New Testing Framework
- [x] Typings improvements
- [ ] Add a few more test cases
- [ ] ESLint checker 
- [ ] Docs

---

OK, so, while this is still early days - we can start using [Jest's Snapshot Testing](http://facebook.github.io/jest/blog/2016/07/27/jest-14.html). It looks a lot like what you were trying to do with mocha/shallow react-native.

IMO this solves a lot of the conceptual problems I was having around figuring out the testing structure. I'll miss [_real_ snapshots](https://github.com/orta/snapshots-peek#an-xcode-plugin-to-give-you-a-preview-of-the-class-youre-looking-at-when-using-fbsnapshots), but I'd trade the visual fidelity for cross-platform and extremely fast, readable JSON.

As a part of this, I studied how [typings](https://github.com/typings/typings) works. I now understand that it's a per-project thing, and you typically do `typings install` in a project to get all the auto-completion working. I have a bunch of staged typing file deletions which will be another second PR.  Too much noise.

I've also got my [JS Dangerfiles](https://github.com/danger/danger/pull/423) fork in, in theory we should get a hello world message from @ArtsyMobile.

Here's an example of what a completed test suite looks like: https://github.com/bartonhammond/snowflake/pull/110

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Hello, world.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by orta** [comment]
I'm gonna wait on adding junit testing, looks like it's on Jest's TODO: https://github.com/facebook/jest/issues/104#issuecomment-233226620

**Comment by orta** [comment]
I had a thought that it might be nice to be able to run those snapshots as storybooks, might ask about it

**Comment by orta** [comment]
Awesome, merging.

**Pull request merged**
