### PR TITLE
Works around Relay compiler issue #trivial

### PR DESCRIPTION
**Pull request by ashfurrow**
See discussion in #1300. This PR simply works around the problem by giving the tests correct, unique query names. I also included the change to our CI setup so we'll catch this problem in the future.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Circle CI wasn't running because no one was following the project? Not sure.

**Comment by ashfurrow** [comment]
Merge on green.

**Comment by orta** [comment]
I think merge on green is well borked

**Comment by ashfurrow** [comment]
Ah, boo.

**Pull request merged**
