### PR TITLE
[BidFlow] Go back to max bid when tapping amount in confirmation screen

### PR DESCRIPTION
**Pull request by mennenia**
For [Purchase-92](https://artsyproduct.atlassian.net/browse/PURCHASE-92)

@yuki24 I had a question about the `ConfirmFirstTimeBid` screen. It's naturally quite similar to the `ConfirmBid`, but kept as a separate component.

Do you know where it gets instantiated? I noticed it doesn't have a `navigator` prop, so I can't pop the screen back. This PR only adds the functionality to the default `ConfirmBid` screen, but I can add it to `ConfirmFirstTimeBid` as well. 

Edit: made it WIP because noticed a few more things in the ticket!

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/artsy/emission/blob/mc-maxbidpop/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx">ConfirmBid-tests.tsx</a>


<li>
<a href='https://github.com/artsy/emission/blob/mc-maxbidpop/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L30'>renders properly</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -190,87 +190,113 @@
          ]
        }
        width="100%"
      />
      <View
-       flexDirection="row"
-       justifyContent="space-between"
-       m={4}
+       accessibilityComponentType={undefined}
+       accessibilityLabel={undefined}
+       accessibilityTraits={undefined}
+       accessible={true}
+       collapsable={undefined}
+       hasTVPreferredFocus={undefined}
+       hitSlop={undefined}
+       isTVSelectable={true}
+       nativeID={undefined}
+       onLayout={undefined}
+       onResponderGrant={[Function]}
+       onResponderMove={[Function]}
+       onResponderRelease={[Function]}
+       onResponderTerminate={[Function]}
+       onResponderTerminationRequest={[Function]}
+       onStartShouldSetResponder={[Function]}
        style={
-         Array [
-           Object {
-             "marginBottom": 20,
-             "marginLeft": 20,
-             "marginRight": 20,
-             "marginTop": 20,
-           },
-           undefined,
-         ]
+         Object {
+           "opacity": 1,
+         }
        }
+       testID={undefined}
+       tvParallaxProperties={undefined}
      >
        <View
-         flex={1}
+         flexDirection="row"
+         justifyContent="space-between"
+         m={4}
          style={
            Array [
              Object {
-               "flexBasis": 0,
-               "flexGrow": 1,
-               "flexShrink": 1,
+               "marginBottom": 20,
+               "marginLeft": 20,
+               "marginRight": 20,
+               "marginTop": 20,
              },
              undefined,
            ]
          }
        >
-         <Text
-           accessible={true}
-           allowFontScaling={true}
-           ellipsizeMode="tail"
-           fontSize={3}
+         <View
+           flex={1}
            style={
              Array [
                Object {
-                 "fontFamily": "AGaramondPro-Semibold",
-                 "fontSize": 16,
+                 "flexBasis": 0,
+                 "flexGrow": 1,
+                 "flexShrink": 1,
                },
                undefined,
              ]
            }
          >
-           Max bid
-         </Text>
-       </View>
-       <View
-         alignItems="flex-end"
-         flex={1}
-         style={
-           Array [
-             Object {
-               "flexBasis": 0,
-               "flexGrow": 1,
-               "flexShrink": 1,
-             },
-             undefined,
-           ]
-         }
-       >
-         <Text
-           accessible={true}
-           allowFontScaling={true}
-           ellipsizeMode="tail"
-           fontSize={3}
+           <Text
+             accessible={true}
+             allowFontScaling={true}
+             ellipsizeMode="tail"
+             fontSize={3}
+             style={
+               Array [
+                 Object {
+                   "fontFamily": "AGaramondPro-Semibold",
+                   "fontSize": 16,
+                 },
+                 undefined,
+               ]
+             }
+           >
+             Max bid
+           </Text>
+         </View>
+         <View
+           alignItems="flex-end"
+           flex={1}
            style={
              Array [
                Object {
-                 "fontFamily": "AGaramondPro-Regular",
-                 "fontSize": 16,
+                 "flexBasis": 0,
+                 "flexGrow": 1,
+                 "flexShrink": 1,
                },
                undefined,
              ]
            }
          >
-           $45,000
-         </Text>
+           <Text
+             accessible={true}
+             allowFontScaling={true}
+             ellipsizeMode="tail"
+             fontSize={3}
+             style={
+               Array [
+                 Object {
+                   "fontFamily": "AGaramondPro-Regular",
+                   "fontSize": 16,
+                 },
+                 undefined,
+               ]
+             }
+           >
+             $45,000
+           </Text>
+         </View>
        </View>
      </View>
      <View
        border={1}
        borderBottomWidth={0}
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:30:21)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by yuki24** [comment]
> Do you know where it gets instantiated?

We haven't wired up this component yet. In [the PR I'm going to send shortly](https://github.com/artsy/emission/compare/PURCHASE-153-2?expand=1), however, we changed the `<ConfirmFirstTimeBid>` component to [implement the `ConfirmBidProps` interface](https://github.com/artsy/emission/blob/24c01c57b6b9351ab3d3fba4af0a5e9b08c28a9a/src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx#L28). The idea is that we can use the `me.has_qualified_credit_cards` flag in the `<SelectMaxBid>` component to show a different screen. I looked into merging these two "Confirm Bid" screens into one, but it seemed a bit too risky to do so since the `<ConfirmBid>` component already has a lot of complicated logic.

There will be some duplicates for sure, and we should refactor and consolidate once we implemented both of them, rather than implementing and consolidating simultaneously.

**Comment by yuki24** [comment]
I just sent #1076 so the `<ConfirmFirstTimeBid>` component gets instantiated when the user doesn't have qualified credit cards.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/artsy/emission/blob/mc-maxbidpop/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx">ConfirmBid-tests.tsx</a>


<li>
<a href='https://github.com/artsy/emission/blob/mc-maxbidpop/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L30'>renders properly</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -67,17 +67,17 @@
          ]
        }
      >
        00
        d
- 
+         
        00
        h
- 
+         
        20
        m
- 
+         
        00
        s
      </Text>
    </View>
    <View>
@@ -127,11 +127,11 @@
              },
              undefined,
            ]
          }
        >
-         Lot
+         Lot 
          538
        </Text>
        <Text
          accessible={true}
          allowFontScaling={true}
@@ -150,11 +150,11 @@
            ]
          }
          textAlign="center"
        >
          Meteor Shower
-         ,
+         , 
          <Text
            accessible={true}
            allowFontScaling={true}
            ellipsizeMode="tail"
            fontSize={2}
@@ -194,54 +194,58 @@
      <View
        accessibilityComponentType={undefined}
        accessibilityLabel={undefined}
        accessibilityTraits={undefined}
        accessible={true}
-       collapsable={undefined}
-       hasTVPreferredFocus={undefined}
+       flexDirection="row"
        hitSlop={undefined}
-       isTVSelectable={true}
+       justifyContent="space-between"
+       m={4}
        nativeID={undefined}
        onLayout={undefined}
        onResponderGrant={[Function]}
        onResponderMove={[Function]}
        onResponderRelease={[Function]}
        onResponderTerminate={[Function]}
        onResponderTerminationRequest={[Function]}
        onStartShouldSetResponder={[Function]}
        style={
-         Object {
-           "opacity": 1,
-         }
+         Array [
+           Object {
+             "marginBottom": 20,
+             "marginLeft": 20,
+             "marginRight": 20,
+             "marginTop": 20,
+           },
+           undefined,
+         ]
        }
        testID={undefined}
-       tvParallaxProperties={undefined}
      >
        <View
-         flexDirection="row"
-         justifyContent="space-between"
-         m={4}
+         flex={1}
          style={
            Array [
              Object {
-               "marginBottom": 20,
-               "marginLeft": 20,
-               "marginRight": 20,
-               "marginTop": 20,
+               "flexBasis": 0,
+               "flexGrow": 1,
+               "flexShrink": 1,
              },
              undefined,
            ]
          }
        >
-         <View
-           flex={1}
+         <Text
+           accessible={true}
+           allowFontScaling={true}
+           ellipsizeMode="tail"
+           fontSize={3}
            style={
              Array [
                Object {
-                 "flexBasis": 0,
-                 "flexGrow": 1,
-                 "flexShrink": 1,
+                 "fontFamily": "AGaramondPro-Semibold",
+                 "fontSize": 16,
                },
                undefined,
              ]
            }
          >
@@ -270,13 +274,12 @@
            ellipsizeMode="tail"
            fontSize={3}
            style={
              Array [
                Object {
-                 "flexBasis": 0,
-                 "flexGrow": 1,
-                 "flexShrink": 1,
+                 "fontFamily": "AGaramondPro-Regular",
+                 "fontSize": 16,
                },
                undefined,
              ]
            }
          >
@@ -402,11 +405,11 @@
                },
                undefined,
              ]
            }
          >
-           You agree to
+           You agree to 
            <Text
              accessible={true}
              allowFontScaling={true}
              ellipsizeMode="tail"
              onPress={[Function]}
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:30:21)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/artsy/emission/blob/mc-maxbidpop/src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx">ConfirmFirstTimeBid-tests.tsx</a>


<li>
<a href='https://github.com/artsy/emission/blob/mc-maxbidpop/src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx#L16'>renders properly</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -188,12 +188,25 @@
          ]
        }
        width="100%"
      />
      <View
+       accessibilityComponentType={undefined}
+       accessibilityLabel={undefined}
+       accessibilityTraits={undefined}
+       accessible={true}
        flexDirection="row"
+       hitSlop={undefined}
        justifyContent="space-between"
+       nativeID={undefined}
+       onLayout={undefined}
+       onResponderGrant={[Function]}
+       onResponderMove={[Function]}
+       onResponderRelease={[Function]}
+       onResponderTerminate={[Function]}
+       onResponderTerminationRequest={[Function]}
+       onStartShouldSetResponder={[Function]}
        p={4}
        style={
          Array [
            Object {
              "paddingBottom": 20,
@@ -202,10 +215,11 @@
              "paddingTop": 20,
            },
            undefined,
          ]
        }
+       testID={undefined}
      >
        <View
          flex={1}
          style={
            Array [
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx:16:21)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/mc-maxbidpop/src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx#L26'>shows the billing address that the user typed in the billing address form</a>
<br/>


<details>
<summary>Full message</summary>
<pre><code>
TypeError: Cannot read property 'component' of undefined
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx:26:10)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by mennenia** [comment]
@yuki24 okay, made the edits! :)

**Comment by yuki24** [comment]
LGTM!

**Pull request merged**
