### PR TITLE
[Danger] Switch to Danger JS #trivial

### PR DESCRIPTION
**Pull request by orta**
Ruby is so 2015.

This moves us to DangerJS 0.0.10 - which should be enough to _not_ be annoying. Does have rough edges though probably. It is enough to be usable in production IMO.

This is the first time I've tried using `require` in a DangerJS file, so err, our milage there may vary.

### CODE REVIEW

**Comment by orta** [comment]
Aww:

```
> emission@1.1.1 danger /home/travis/build/artsy/emission
> danger
OK
module.js:440
    throw err;
    ^
Error: Cannot find module './travis'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/artsy/emission/node_modules/danger/distribution/ci_source/ci_source.js:11:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by ArtsyOpenSource** [comment]
OK

**Comment by orta** [comment]
OK, so it was a syntax error in my Dangerfile

**Comment by orta** [comment]
OK, this is good to go on green.

**Pull request merged**
