### PR TITLE
[Dev] Provide advice on how to clone, and provide a checklist for signing

### PR DESCRIPTION
**Pull request by orta**
This is WIP - need to null out whether the tick is checked in the "has this been changed" and thus needs to update.

<hr data-danger="yep"/>

### Tested on Device?

- [ ] @orta
- [ ] @alloy
- [ ] @l2succes
- [ ] @mennenia
- [ ] @sarahscott

<details>
  <summary>How to get set up with this PR?</summary>
  <p>&nbsp;</p>
   <p><b>To run on your computer:</b></p>
<pre><code>git fetch origin pull/558/head:orta-558-checkout
git checkout orta-558-checkout
yarn install
cd example; pod install; cd ..
open -a Simulator
yarn start</code></pre>
   </p>
   <p>Then run <code>xcrun simctl launch booted net.artsy.Emission</code> once a the simulator has finished booting</p>
   <p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
   <p>If you see <i>"Use Staging React Env" </i> - click that and restart, then follow the next step.</p>
   <p>Click on <i>"Choose an RN build" </i> - then pick the one that says: "X,Y,Z"</p>
   <p>Note: this is a TODO for PRs, currently  you can only do it on master commits.</p>
</details>

### CODE REVIEW

**Comment by orta** [comment]
Doing many peeps so I can see if it handles that correct

**Comment by mennenia** [comment]
Huh, the formatting broke in this one? :o

**Comment by orta** [comment]
Thanks - fixed, being redeployed atm

**Comment by orta** [comment]
OK, it'll now it won't reset the ticks on new danger runs. I think, we'll find out if mine + @mennenia's ticks disappear.

**Comment by orta** [comment]
Aww, it did. Hrm.

**Comment by orta** [comment]
❓ Anyone got an idea, this looks like I'd expect. 

```js
> const a = "- [x] asdasdasdda;\n - [ ] asdazzxxzxc".replace(/- \[*.\]/g, "---")
undefined
> const b = "- [x] asdasdasdda;\n - [x] asdazzxxzxc".replace(/- \[*.\]/g, "---")
undefined
> a === b
true
```

Wonder if there's an extra newline somewhere.

**Comment by ArtsyOpenSource** [comment]
Now:
This is WIP - need to null out whether the tick is checked in the "has this been changed" and thus needs to update.



<hr data-danger="yep"/>

### Tested on Device?

- @orta
- @alloy
- @l2succes
- @mennenia
- @sarahscott

<details>
  <summary>How to get set up with this PR?</summary>
  <p>&nbsp;</p>
   <p><b>To run on your computer:</b></p>
<pre><code> git fetch origin pull/558/head:orta-558-checkout
git checkout orta-558-checkout
yarn install
cd example; pod install cd ..
yarn ios
yarn start</code></pre>
   </p>
   <p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
   <p>If you see <i>"Use Staging React Env" </i> - click that and restart, then follow the next step.</p>
   <p>Click on <i>"Choose an RN build" </i> - then pick the one that says: "X,Y,Z"</p>
   <p>Note: this is a TODO for PRs, currently  you can only do it on master commits.</p>
</details>


New:
This is WIP - need to null out whether the tick is checked in the "has this been changed" and thus needs to update.




<hr data-danger="yep"/>

### Tested on Device?

- @orta
- @alloy
- @l2succes
- @mennenia
- @sarahscott

<details>
  <summary>How to get set up with this PR?</summary>
  <p>&nbsp;</p>
   <p><b>To run on your computer:</b></p>
<pre><code>git fetch origin pull/558/head:orta-558-checkout
git checkout orta-558-checkout
yarn install
cd example; pod install cd ..
yarn ios
yarn start</code></pre>
   </p>
   <p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
   <p>If you see <i>"Use Staging React Env" </i> - click that and restart, then follow the next step.</p>
   <p>Click on <i>"Choose an RN build" </i> - then pick the one that says: "X,Y,Z"</p>
   <p>Note: this is a TODO for PRs, currently  you can only do it on master commits.</p>
</details>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
It looks like it was whitespacing 

screen shot 2017-05-23 at 10 27 26

**Comment by orta** [comment]
👍

**Comment by l2succes** [comment]
screen shot 2017-05-23 at 12 20 37 pm

@orta not sure why but `yarn ios` doesn't work for me so I have to run Xcode manually. Not a blocker but making a note in case it happens to other people.

**Comment by orta** [comment]
To my knowledge it doesn't do much - we might be able to replicate it from our  side pretty easily, we'd need a command that opens the right sim, then with the right app

**Comment by orta** [comment]
In theory it can be:

```
open -a Simulator
echo "Once the simulator has loaded: xcrun simctl launch booted net.artsy.Emission"
```

**Comment by sarahscott** [comment]
Very small thing but `cd example; pod install cd ..` should be `cd example; pod install; cd ..`

**Comment by sarahscott** [comment]
Otherwise the setup instructions work for me!

**Comment by orta** [comment]
Good catch - I have enough open PRs, so self-merging this 👍

**Pull request merged**
