### PR TITLE
Update react-native types to latest version of PR.

### PR DESCRIPTION
**Pull request by alloy**
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15105

The gist of it is that the default `ReactNative` namespace is gone.

### CODE REVIEW

**Comment by sarahscott** [comment]
Travis is upset by `yarn install`

**Comment by alloy** [comment]
Yeah what’s up with that?

I just ran locally and actually see there’s 2 test failures, will fix in a bit.

**Comment by orta** [comment]
This got merged to def types, and I fixed the travis/yarn issue

**Comment by orta** [comment]
Should just need a rebase

**Comment by alloy** [comment]
Updated.

**Comment by alloy** [comment]
Danger appears to be failing internally, everything else is green.

**Comment by sarahscott** [comment]
Woohoo - looks much cleaner.

**Pull request merged**
