### PR TITLE
Clean dependencies #trivial

### LINKED ISSUE #559: Improve the ability to introspect rendered react trees
Right now we're using jest-snapshots to say "this is the whole structure" of a react tree. We use those tests to verify that is what we want, but those tests are a really thick brush and say nothing about behaviours that you expect.

I'd like to write some tests that verify the behaviour of the react tree, for example:

```js
it("shows an image with the number of images when passed image data", () => {
 state = {
   photos: ["url1", "url2", "url3"],
 }
 const todo = renderer.create(<TODO {...state}/>).toJSON()
 const image = getComponent(todo, "Background Button[1] ImagePreview")
 expect(image).toBeTruthy()

 const text = getComponent(image, "ImagePreview ImageDarkener InlineCopy")
 expect(text.text).toEqual(3)
})
```

So we could consider looking into what the minimal parts of [Enzyme](https://github.com/airbnb/enzyme) can be found that work with react-test-renderer.

### PR DESCRIPTION
**Pull request by alloy**
Closes #559

# Number of deps before

1004

# Number of deps after

965

### CODE REVIEW

**Comment by orta** [comment]
I thought Enzyme was in active use? https://github.com/artsy/emission/issues/559

**Comment by alloy** [comment]
Enzyme is a bottleneck to upgrading, it doesn’t work the React 16 alpha that RN uses atm and it’s likely to happen again in the future: https://github.com/artsy/emission/issues/577.

I don’t know what was previously using it, it was probably just left behind after somebody tried to use it.

**Comment by orta** [comment]
Looks like it got removed from the codebase two days ago 👍

**Comment by sarahscott** [comment]
👌

**Pull request merged**
