### PR TITLE
@alloy => [Messaging] Fix incorrect use of AttachmentPreview and props

### PR DESCRIPTION
**Pull request by mzikherman**
Thx for pointing it out, I don't see the warning anymore (and I did on `master` - sorry!).

### CODE REVIEW

**Comment by orta** [comment]
I wonder if it's worth getting Danger to look for warnings during a test run, there's already a few in there

**Comment by mzikherman** [comment]
Not sure why this eventually failed with `exit code 1` https://travis-ci.org/artsy/emission/builds/268444823?utm_source=github_status&utm_medium=notification (everything looks successful?).

**Comment by orta** [comment]
It was the commit deployer, those should probably turn into `./script && true`

**Comment by alloy** [comment]
Alright, then I’m merging, the PR looks good to me 👍

**Pull request merged**
