### PR TITLE
Purchase 145 fix bid status update

### PR DESCRIPTION
**Pull request by erikdstock**
Tracked in https://artsyproduct.atlassian.net/browse/PURCHASE-145

This updates Emission to use the NSNotificationCenter notification name that Eigen [listens for](https://github.com/artsy/eigen/blob/c8efe6092a8a73953650ff7cb1802839819b3aa9/Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m#L107-L109) when a bid is updated.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  No CHANGELOG added.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx">ConfirmBid-tests.tsx</a>


<li>
<a href='https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L118'>polls for new results</a>
<br/>


<details>
<summary>Full message</summary>
<pre><code>
TypeError: Cannot read property 'component' of undefined
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:118:14)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L137'>shows error when polling attempts exceed max</a>
<br/>


<details>
<summary>Full message</summary>
<pre><code>
TypeError: Cannot read property 'component' of undefined
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:137:14)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L153'>shows successful bid result when highest bidder</a>
<br/>


<details>
<summary>Full message</summary>
<pre><code>
TypeError: Cannot read property 'component' of undefined
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:153:14)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L168'>shows outbid bidSuccessResult when outbid</a>
<br/>


<details>
<summary>Full message</summary>
<pre><code>
TypeError: Cannot read property 'component' of undefined
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:168:14)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L183'>shows reserve not met when reserve is not met</a>
<br/>


<details>
<summary>Full message</summary>
<pre><code>
TypeError: Cannot read property 'component' of undefined
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:183:14)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx#L193'>shows the error screen with a failure</a>
<br/>


<details>
<summary>Full message</summary>
<pre><code>
TypeError: Cannot read property 'postNotificationName' of undefined
    at ConfirmBid.presentBidResult (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/ConfirmBid.tsx:178:5)
    at ConfirmBid.verifyBidPosition (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/ConfirmBid.tsx:145:12)
    at onCompleted (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/ConfirmBid.tsx:118:14)
    at /home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:193:9
    at /home/travis/build/artsy/emission/node_modules/jest-environment-node/node_modules/jest-mock/build/index.js:372:37
    at mockConstructor (/home/travis/build/artsy/emission/node_modules/jest-environment-node/node_modules/jest-mock/build/index.js:109:19)
    at ConfirmBid.placeBid (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/ConfirmBid.tsx:116:5)
    at Object._react2.default.createElement._react2.default.createElement._react2.default.createElement._react2.default.createElement._react2.default.createElement.onPress (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/ConfirmBid.tsx:246:74)
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx:196:56)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx">BidFlow-tests.tsx</a>


<li>
<a href='https://github.com/artsy/emission/blob/PURCHASE-145-fix-bid-status-update/src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx#L65'>allows bidders with a qualified credit card to bid</a>
<br/>
Expected value to equal: "You're the highest bidder", received: "Confirm your bid"

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(received).toEqual(expected)

Expected value to equal:
  "You're the highest bidder"
Received:
  "Confirm your bid"
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx:65:32)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by yuki24** [comment]
LGTM!

**Comment by yuki24** [comment]
Oops

**Comment by yuki24** [comment]
O

**Comment by yuki24** [comment]
Apologies for the noise. I was trying to merge this on the phone.

**Comment by yuki24** [comment]
Merge on green

**Comment by yuki24** [comment]
There's a conflict that needs to be resolved. Feel free to merge once it's resolved.

**Pull request merged**
