### PR TITLE
Add an automated setup script

### PR DESCRIPTION
**Pull request by orta**
I had to re-install my repo from scratch after getting #632 merged, due to caps issues (that PR predated the first major capitalisation changes) 

Setting up the project takes a bunch of commands, and every time I blow the repo, I forget the commit hooks. So I've automated that away. Opted for `make oss` as that's consistent with other Artsy mobile projects.

### CODE REVIEW

**Comment by orta** [comment]
Looks like:
screen shot 2017-07-13 at 14 23 57

**Comment by orta** [comment]
Him, are those really the best instructions - it doesn't tell you how to start the app in the sim etc

**Comment by orta** [comment]
Better:

screen shot 2017-07-13 at 14 28 52

Think it's fine to recommend doing it via Xcode, you get to see the console logs etc too then

**Comment by alloy** [comment]
Nice 👌

**Pull request merged**
