### PR TITLE
Update Danger - #trivial

### PR DESCRIPTION
**Pull request by orta**
Not much of a PR, just figured I'd keep it up to date.

### CODE REVIEW

**Comment by orta** [comment]
lols, 2 days later we're already on danger `0.18`

**Comment by orta** [comment]
This PR is so stale. :D

**Comment by orta** [comment]
@sarahscott @alloy @l2succes this also updates the snapshots to the new version (only difference is that they have a version number at the top)

**Comment by orta** [comment]
And is now ready for review.

**Comment by alloy** [comment]
✨

**Pull request merged**
