### PR TITLE
Update ts, relay plugin, relay typings

### PR DESCRIPTION
**Pull request by ds300**
Taking advantage of https://github.com/relay-tools/relay-compiler-language-typescript/pull/139

#trivial

### CODE REVIEW

**Comment by alloy** [comment]
Noice! 🤘 

What for do we need `@types/relay-compiler` ?

**Comment by ds300** [comment]
We do not, removed.

**Comment by ds300** [comment]
something weird going on with travis again. looks like auth misconfiguration.

**Comment by alloy** [comment]
:shipit:

**Comment by artsyit** [comment]
:rocket: PR was released in v1.18.1 :rocket:

**Pull request merged**
