### PR TITLE
Sets up making sure there's a phone number on a users's account when signing up for an auction

### PR DESCRIPTION
**Pull request by orta**
Supports ensuring that the phone number is set when signing up for an auction

### CODE REVIEW

**Comment by sweir27** [comment]
@orta 🤞 that the tests are green now! I also added a few more for the reg flow.

**Comment by orta** [comment]
OK, yep, I've given it a run through locally since upgrading to RN 0.57  (and made a minor test refactor) 

All looks good - merge on green

**Comment by orta** [comment]
This'll be blocked on a beta until LD launch, but will come out in the next patch after that

**Comment by sweir27** [comment]
Thanks @orta !

**Pull request merged**
