### PR TITLE
Fix a bug where infinite scroll doesn't know how to stop unless you use a finished callback

### PR DESCRIPTION
**Pull request by orta**
Found while debugging #578

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  [danger-plugin-jest] Could not read test results. Danger cannot pass or fail the build.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by alloy** [comment]
Hmm, is that a test failure? Couldn’t easily parse the output

**Comment by orta** [comment]
Yeah, it looks like Jest is dying entirely from this

**Comment by orta** [comment]
Didn't fail locally though:

```
Test Suites: 100 passed, 100 total
Tests:       2 skipped, 225 passed, 227 total
Snapshots:   117 passed, 117 total
Time:        37.294s
Ran all test suites.
✨  Done in 39.57s.
```

**Comment by alloy** [comment]
Ahhh, try running locally with `--runInBand`?

**Comment by orta** [comment]
Ding.

screen shot 2018-01-08 at 4 57 48 pm

**Comment by orta** [comment]
So weird, completely unrelated section of code

**Comment by alloy** [comment]
Might be async code that’s failing outside of the boundaries of an `it` closure?

**Comment by orta** [comment]
Nope, commenting out the `it`'s  body skips the crash: 

```
  // const tree = renderer.create(<Inquiry artwork={inquiryProps} />).toJSON()
  // expect(tree).toMatchSnapshot()
```

**Comment by orta** [comment]
ish,  `Composer-tests.tsx` fails it instead

**Comment by alloy** [comment]
Maybe you’re commenting out tests that run _after_ the test that triggered the async code?

**Comment by alloy** [comment]
My hypothesis is that it works when ran in external processes, because the process exits successfully _before_ the async code triggers the exception.

**Comment by alloy** [comment]
Going to merge this as-is and look into CI issues tomorrow.

**Pull request merged**
