### PR TITLE
[Home] Switchboard now supports search

### PR DESCRIPTION
**Pull request by sarahscott**
- [x] Added search to emission's switchboard
- [x] Update Emission pod's `ARSwitchboardModule` and eigen's `ARAppDelegate+Emission` with my changes

search

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG added.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">The following files do not have tests: <a href="https://github.com/artsy/emission/blob/1bd8aa752a07d36359199201b75b139f230ad9cd/lib/components/home/search_bar.js">lib/components/home/search_bar.js</a> &amp; <a href="https://github.com/artsy/emission/blob/1bd8aa752a07d36359199201b75b139f230ad9cd/lib/native_modules/switch_board.js">lib/native_modules/switch_board.js</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by alloy** [comment]
I wonder if we should really add a new callback for this or instead maybe use the `presentModalViewController` one with route `/search`. Did you consider that and, if so, what was the reason you decided against it?

**Comment by sarahscott** [comment]
I hadn't looked into that but if it simplifies things, I'm open to the idea. I wanted to figure out a convenient way to call `showSearch` from `ARNavigationController` - do you think that would be easier achieved by a new route instead of a new callback?

**Comment by alloy** [comment]
@sarahscott I’d like the API surface of the Emission pod to remain simple and leave it up to the host app to special case where needed.

**Comment by sarahscott** [comment]
@alloy this should be good to go

**Comment by alloy** [comment]
So lean 👌

**Pull request merged**
