### PR TITLE
Consolidate the bid information row #trivial

### PR DESCRIPTION
**Pull request by yuki24**
The styles for the bid information row has been stable and I think it's time to consolidate it. There are other low-hanging fruit but I left it and keep this PR small and simple

#skip_new_tests

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Missing Test Files:

- `src/lib/Components/Bidding/Components/__tests__/BidInfoRow-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by sweir27** [comment]
Nice! Looks like a great optimization. 💅

**Comment by sweir27** [comment]
Gah, looks like an actual rebase is needed here 😢

**Comment by yuki24** [comment]
rebased and resolved the conflict.

**Pull request merged**
