### PR TITLE
[WIP] Keep trying to automate release

### PR DESCRIPTION
**Pull request by ds300**
#trivial

### CODE REVIEW

**Comment by artsyit** [comment]
:rocket: PR was released in v1.12.14 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v1.12.14 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v1.12.14 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v1.12.14 :rocket:

**Comment by ds300** [comment]
hahah well the auto stuff is working. Only problem is doing it in this branch leads to a push/CI cycle. Another problem was that auto seemed to be going back through every PR and adding comments to say they'd shipped, so I cancelled the job. Need to find out why and see if we can mitigate while we keep working on it.

**Comment by ds300** [comment]
closing after having completed this work in #1935

**Pull request closed without merging**
