### PR TITLE
[WIP][dev] Upgrades RN to v0.48.0

### PR DESCRIPTION
**Pull request by sarahscott**
This branch is in a state where everything should be able to run as expected, with the exception of nested scrollviews (e.g. an Artist's Artworks masonry grid). It requires a monkey-patched version of Relay with a small change re: `unstable_batchedUpdates`; I have the change locally and can help someone out with it if they would like to use this branch before it is merged. 

- [x] Upgrade RN
- [ ] Decide how to deal with the Relay monkey patch (on @alloy's custom branch perhaps?)
- [ ] Fix nested scrollviews (everything should run without crashing but `onScroll` callbacks will not be called; the `RCTScrollView` API has changed considerably so this might take a bit of time)
- [x] Adapt usage of `NetInfo` to new API (the `change` event is now deprecated)
- [x] Tests

Please feel free to add to the above list.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: TypeError

```sh
TypeError: Cannot read property '' of undefined
    at ModuleMap._getModuleMetadata (/home/travis/build/artsy/emission/node_modules/jest-haste-map/build/module_map.js:84:30)
    at ModuleMap.getModule (/home/travis/build/artsy/emission/node_modules/jest-haste-map/build/module_map.js:40:25)
    at Resolver.getModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:191:28)
    at Resolver._isModuleResolved (/home/travis/build/artsy/emission/node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:300:20)
    at Resolver._getAbsolutPath (/home/travis/build/artsy/emission/node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:277:17)
    at Resolver.getModuleID (/home/travis/build/artsy/emission/node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:252:31)
    at Runtime.requireModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/build/index.js:276:37)
    at /home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:133:33
    at ensureCleanDangerfile (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:173:5)
    at Object.<anonymous> (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:132:21)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by alloy** [comment]
Yeah I should probably merge yours into mine. Also note that RN 0.48 proper has been released by now, let’s use that.

**Comment by alloy** [comment]
This works now 👌

I’m gonna merge it into my Relay Modern PR 👍

**Comment by alloy** [comment]
Done.

**Pull request closed without merging**
