### PR TITLE
Update Danger + Jest

### PR DESCRIPTION
**Pull request by orta**
Danger didn't let us know about the CHANGELOG warning in https://github.com/artsy/emission/pull/419

I have an issue about this, still not quite figured it, but Danger has had a bunch of updates since this build.

Also updated Jest, don't think we have any breaking changes there.

### CODE REVIEW

**Comment by orta** [comment]
Build wasn't failing because [travis wouldn't fail](https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build) on things after `script`.

**Comment by alloy** [comment]
Ok, so now the build is thoroughly 🔴 

Are changes for that forthcoming too?

**Comment by orta** [comment]
Yep, there we go

**Comment by orta** [comment]
if this greens, we're good to go

**Comment by orta** [comment]
Yep @alloy

**Comment by alloy** [comment]
Aces 👍

**Pull request merged**
