### PR TITLE
[Consignments] Add new icons to welcome screen

### PR DESCRIPTION
**Pull request by mennenia**
woooo!! thanks @katarinabatina for the gorg icons :D  

Please note, iPad fixes are on a different branch, so not part of this beta :(

simulator screen shot - iphone 6 - 9 1 - 2017-12-12 at 17 52 51

#trivial

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  No CHANGELOG added.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
Do you need to delete the old ones @mennenia?

**Comment by mennenia** [comment]
@orta no, those are for the inbox zero view. I just used them again here :)

**Comment by orta** [comment]
👍

**Pull request merged**
