### PR TITLE
Added a Home container

### PR DESCRIPTION
**Pull request by sarahscott**
I am getting this error: ``Application Artist has not been registered``
I tried changing things in the app registry and relay routes but to no avail.

### CODE REVIEW

**Comment by alloy** [comment]
Works!

⚠️  However, this depends on both https://github.com/artsy/metaphysics/pull/313 and https://github.com/artsy/metaphysics/pull/337 to be merged first, so don’t merge yet.

simulator screen shot 05 jul 2016 17 23 41

**Comment by mennenia** [comment]
yay!

**Comment by orta** [comment]
Cool

**Comment by alloy** [comment]
This can now be merged.

**Pull request merged**
