### PR TITLE
[Home] Re-align headers of various tabs.

### PR DESCRIPTION
**Pull request by alloy**
Fixes https://github.com/artsy/collector-experience/issues/868

screen shot 2018-01-05 at 23 00 46

screen shot 2018-01-05 at 23 01 22

screen shot 2018-01-05 at 23 01 53

#skip_new_tests

### CODE REVIEW

**Comment by alloy** [comment]
Just pushing some pixels around.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Missing Test Files:

- `src/lib/Scenes/Home/Components/ForYou/__tests__/index-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "#skip_new_tests".
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/artsy/emission/blob/fix-margin-on-artists-and-auctions-tabs/src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx">index-tests.tsx</a>


<li>
<a href='https://github.com/artsy/emission/blob/fix-margin-on-artists-and-auctions-tabs/src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx#L17'>looks correct when rendered</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -131,15 +131,10 @@
    onViewableItemsChanged={undefined}
    refreshControl={
      <RefreshControlMock
        onRefresh={[Function]}
        refreshing={false}
-       style={
-         Object {
-           "marginBottom": 20,
-         }
-       }
      />
    }
    renderItem={[Function]}
    scrollEventThrottle={50}
    sections={
@@ -277,11 +272,11 @@
                  "backgroundColor": "white",
                  "marginBottom": -4,
                  "paddingBottom": 0,
                  "paddingLeft": 10,
                  "paddingRight": 10,
-                 "paddingTop": 47,
+                 "paddingTop": 25,
                },
                undefined,
              ]
            }
          >
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx:17:10)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
    at tryCallTwo (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:66:3)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
    at tryCallOne (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:37:12)
    at /home/travis/build/artsy/emission/node_modules/promise/lib/core.js:123:15
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/artsy/emission/blob/fix-margin-on-artists-and-auctions-tabs/src/lib/Containers/__tests__/WorksForYou-tests.tsx">WorksForYou-tests.tsx</a>


<li>
<a href='https://github.com/artsy/emission/blob/fix-margin-on-artists-and-auctions-tabs/src/lib/Containers/__tests__/WorksForYou-tests.tsx#L30'>lays out correctly on small screens</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -3,15 +3,10 @@
    onScroll={[Function]}
    refreshControl={
      <RefreshControlMock
        onRefresh={[Function]}
        refreshing={false}
-       style={
-         Object {
-           "marginBottom": 20,
-         }
-       }
      />
    }
    scrollEventThrottle={100}
  >
    <RCTRefreshControl />
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Containers/__tests__/WorksForYou-tests.tsx:30:12)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
    at tryCallTwo (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:66:3)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
    at tryCallOne (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:37:12)
    at /home/travis/build/artsy/emission/node_modules/promise/lib/core.js:123:15
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/fix-margin-on-artists-and-auctions-tabs/src/lib/Containers/__tests__/WorksForYou-tests.tsx#L36'>lays out correctly on larger screens</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -3,15 +3,10 @@
    onScroll={[Function]}
    refreshControl={
      <RefreshControlMock
        onRefresh={[Function]}
        refreshing={false}
-       style={
-         Object {
-           "marginBottom": 20,
-         }
-       }
      />
    }
    scrollEventThrottle={100}
  >
    <RCTRefreshControl />
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Containers/__tests__/WorksForYou-tests.tsx:36:12)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
    at tryCallTwo (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:66:3)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
    at tryCallOne (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:37:12)
    at /home/travis/build/artsy/emission/node_modules/promise/lib/core.js:123:15
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/fix-margin-on-artists-and-auctions-tabs/src/lib/Containers/__tests__/WorksForYou-tests.tsx#L68'>lays out correctly on small screens</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -7,15 +7,10 @@
    onScroll={[Function]}
    refreshControl={
      <RefreshControlMock
        onRefresh={[Function]}
        refreshing={false}
-       style={
-         Object {
-           "marginBottom": 20,
-         }
-       }
      />
    }
    scrollEventThrottle={100}
  >
    <RCTRefreshControl />
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Containers/__tests__/WorksForYou-tests.tsx:68:12)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
    at tryCallTwo (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:66:3)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
    at tryCallOne (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:37:12)
    at /home/travis/build/artsy/emission/node_modules/promise/lib/core.js:123:15
</code></pre>
</details>
</li>
<br/>



<li>
<a href='https://github.com/artsy/emission/blob/fix-margin-on-artists-and-auctions-tabs/src/lib/Containers/__tests__/WorksForYou-tests.tsx#L74'>lays out correctly on larger screens</a>
<br/>
Snapshot has changed

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -7,15 +7,10 @@
    onScroll={[Function]}
    refreshControl={
      <RefreshControlMock
        onRefresh={[Function]}
        refreshing={false}
-       style={
-         Object {
-           "marginBottom": 20,
-         }
-       }
      />
    }
    scrollEventThrottle={100}
  >
    <RCTRefreshControl />
    at Object.<anonymous> (/home/travis/build/artsy/emission/src/lib/Containers/__tests__/WorksForYou-tests.tsx:74:12)
    at Object.asyncFn (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
    at resolve (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
    at tryCallTwo (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:66:3)
    at mapper (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
    at promise.then (/home/travis/build/artsy/emission/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
    at tryCallOne (/home/travis/build/artsy/emission/node_modules/promise/lib/core.js:37:12)
    at /home/travis/build/artsy/emission/node_modules/promise/lib/core.js:123:15
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
Ah, you just missed the emission beta 13 train - shoulda asked, but it didn't seem like anyone was active in slack

**Comment by alloy** [comment]
Aww :(

**Comment by alloy** [comment]
This is good 👍

**Comment by orta** [comment]
This image looks like glitch art

**Pull request merged**
