### PR TITLE
[Home][ArtistRail] Added header and separator to artist rail

### PR DESCRIPTION
**Pull request by sarahscott**
- [x] Separator for artist rail
- [x] Fixed header for artist rail
- [x] iPhone polish
- [x] iPad polish

simulator screen shot aug 26 2016 12 18 18 pm

### CODE REVIEW

**Comment by alloy** [comment]
So pretty!

Two questions:
1. Did you really intend to update the JS bundle? If not, can you remove it from your patch please?
2. What is the “iPad polish” about, just the general stuff including 4 column grids? If so, that can be deferred to another PR and this one can be wrapped up first.

**Comment by sarahscott** [comment]
iPad polish should take about 5 more minutes - I'm just tweaking margins/font sizes. And woops - I didn't mean to commit the jsbundle changes.... RN got confused when I changed `SectionHeader` to `SectionTitle` but it's all good now.

**Comment by ArtsyMobile** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG added.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">The following files do not have tests: <a href="https://github.com/artsy/emission/blob/c9b7d750a5a1e934defd7d9c3624fa6c1644d47d/lib/components/home/artist_rails/artist_rail.js">lib/components/home/artist_rails/artist_rail.js</a>, <a href="https://github.com/artsy/emission/blob/c9b7d750a5a1e934defd7d9c3624fa6c1644d47d/lib/components/home/artwork_rails/artwork_rail_header.js">lib/components/home/artwork_rails/artwork_rail_header.js</a>, <a href="https://github.com/artsy/emission/blob/c9b7d750a5a1e934defd7d9c3624fa6c1644d47d/lib/components/home/section_header.js">lib/components/home/section_header.js</a> &amp; <a href="https://github.com/artsy/emission/blob/c9b7d750a5a1e934defd7d9c3624fa6c1644d47d/lib/components/home/section_title.js">lib/components/home/section_title.js</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mennenia** [comment]
Looks aahhmaazing! :D

**Pull request merged**
