### PR TITLE
[dev] Convert to use Sentry 3.0

### PR DESCRIPTION
**Pull request by orta**
This moves Emission _back_ to be a static library by migrating to the 3.0 release, so that there are less issues with deployment which deprecates https://github.com/artsy/emission/pull/574

This has forks for both Sentry  https://github.com/getsentry/sentry-cocoa/pull/171 + SentryReactNative  https://github.com/getsentry/react-native-sentry/pull/84

Looks like the sentry PR failed their CI though, so I'll need to look at that. 

Re: https://github.com/artsy/emission-nebula/issues/3<hr data-danger="yep"/>

### Tested on Device?

- [ ] @orta
- [ ] @alloy
- [ ] @orta

<details>
  <summary>How to get set up with this PR?</summary>
  <p>&nbsp;</p>
   <p><b>To run on your computer:</b></p>
<pre><code>git fetch origin pull/584/head:orta-584-checkout
git checkout orta-584-checkout
yarn install
cd example; pod install; cd ..
open -a Simulator
yarn start</code></pre>
   </p>
   <p>Then run <code>xcrun simctl launch booted net.artsy.Emission</code> once a the simulator has finished booting</p>
   <p><b>To run inside Eigen (prod or beta) or Emission (beta):</b> Shake the phone to get the Admin menu.</p>
   <p>If you see <i>"Use Staging React Env" </i> - click that and restart, then follow the next step.</p>
   <p>Click on <i>"Choose an RN build" </i> - then pick the one that says: "X,Y,Z"</p>
   <p>Note: this is a TODO for PRs, currently  you can only do it on master commits.</p>
</details>

### CODE REVIEW

**Comment by orta** [comment]
All in all, this looks pretty 👍 

Still not really sure why emission-nebula is not passing now: https://travis-ci.org/artsy/emission-nebula

Gonna have to get it all running locally and test tomorrow morning.

**Comment by orta** [comment]
OK - this should get reviewed and merged, I'll do a manual deploy to TestFlight when this is in 👍

**Comment by orta** [comment]
Ah wait, I'll take us off my forks - theres new versions of sentry/sentryrn with my changes

**Comment by orta** [comment]
OK, this is 👍

**Comment by alloy** [comment]
👍

**Pull request merged**
