### PR TITLE
@mennenia => [Messaging] An attempt at using react-native-hyperlink to linkify text

### PR DESCRIPTION
**Pull request by mzikherman**
Uses https://github.com/obipawan/react-native-hyperlink to present tappable links. This may not be the best way to do it (maybe we should use `Linking` or something else- I'm a bit unfamiliar with popping open views), but it's a start!

(there's a hyperlink to google in the text)

bp

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  No CHANGELOG added.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by mennenia** [comment]
so HyperLink automatically detects the link in the body text? That's amazing! 

I think it's fine to use `SwitchBoard` to open the URLs, that way the links stay within the app and whatever happens, it will be consistent throughout. If we'd want to open them in Safari, well, we can always tackle that if and when necessary :). 

We don't have a link style do we? Is there a specific way it's displayed in CMS that we know? cc/ @katarinabatina 

@mzikherman anything else you think you need before you want to merge? (title still says WIP, though it's lookin' ✨ )

**Comment by l2succes** [comment]
I tested this locally and it'll take care of the use cases we consider to be showstoppers (i.e. urls like http://www.artsy.net, www.artsy.net)

https://github.com/artsy/collector-experience/issues/391

**Comment by mennenia** [comment]
🙌

**Comment by katarinabatina** [comment]
https://github.com/artsy/collector-experience/issues/528

ticket for styling the link

**Pull request merged**
