### PR TITLE
Update `sync-schema` workflow

### PR DESCRIPTION
**Pull request by alloy**
It will now be easy for anyone to update our copy of metaphysics’ schema.

### CODE REVIEW

**Comment by orta** [comment]
Is this schema used in the app anywhere?

**Comment by alloy** [comment]
@orta Relay uses the JSON version to validate the queries you build. The GraphQL version is meant for us to be able to easily check the schema.

**Comment by alloy** [comment]
https://facebook.github.io/relay/docs/guides-babel-plugin.html#schema-json

**Comment by orta** [comment]
Perfect, that's the link I was looking for

**Comment by orta** [comment]
I don't know where the abstractions start / stop yet once this is back in eigen, but it may be worth adding a `make metaphysics_schema` action that triggers `npm blah blah` this to make it consistent with the rest of the app

**Comment by alloy** [comment]
That command is only needed while working on Emission, but I’ll definitely bridge whatever commands are needed in Eigen 👍

**Comment by sarahscott** [comment]
👍

**Pull request merged**
