### PR TITLE
Adds Sale container to app registry

### PR DESCRIPTION
**Pull request by ashfurrow**
This adds the Sale container to the app registry, the first steps to exposing it to Eigen as a native view controller.

### CODE REVIEW

**Comment by orta** [comment]
TSLint fail is legit - 

```sh
ERROR: src/lib/AppRegistry.tsx[14, 3]: Named imports must be alphabetized.
ERROR: src/lib/Containers/index.tsx[6, 1]: Import sources within a group must be alphabetized.
```

**Comment by orta** [comment]
We should really consider making Emission use the commit linter checks by default like our other repos, @ashfurrow you need to run [these commands](https://github.com/artsy/emission/blob/master/Makefile#L34)

**Comment by ashfurrow** [comment]
Thanks Orta, I forgot they don't get run on this repo. I'm 👍 for enabling them by default!

**Comment by ashfurrow** [comment]
Tests passed but Danger failed because I accidentally made the PR from a fork. Want me to open a new PR?

**Comment by ashfurrow** [comment]
Tests passed but Danger failed because I accidentally made the PR from a fork. Want me to open a new PR?

**Comment by ashfurrow** [comment]
Tests passed but Danger failed because I accidentally made the PR from a fork. Want me to open a new PR?

**Comment by orta** [comment]
Using a fork too? What has become of you in your time away Ash? I'm ok with this, it's just danger failing because it can't get access to the token

**Comment by orta** [comment]
Using a fork too? What has become of you in your time away Ash? I'm ok with this, it's just danger failing because it can't get access to the token

**Comment by ashfurrow** [comment]
It was an accident I swear!

**Pull request merged**
