### PR TITLE
[Crash] guard against conversations_existence_check being null

### PR DESCRIPTION
**Pull request by xtina-starr**
**The error message caused by `this.props.me.conversations_existence_check` being `null`:**
simulator screen shot - iphone 6 - 2017-11-01 at 17 11 31

**After the null check:**
simulator screen shot - iphone 6 - 2017-11-01 at 17 10 14

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  No CHANGELOG added.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
Awesome work - CHANGELOG please 👍

**Comment by mzikherman** [comment]
Ah, sorry we discussed offline:

This is a temporary issue due to a switch in some authentication thats out on staging currently. While there's nothing wrong with being extra defensive (IMO), we should understand and reason about the data we get back and only be defensive on _actual_ scenarios, so we'll close for now.

Although...I suppose being defensive, even in a total red herring scenario thats _not_ expected, is probably better than an outright crash, no? In that case maybe we should merge this in!

Reopening!

**Comment by mennenia** [comment]
So that's what I was wondering... I think it's always worth guarding against a crash, though @xtina-starr rightly mentioned... maybe it _should_ actually crash if something is truly amiss?

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  No CHANGELOG added.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by mzikherman** [comment]
Let's CHANGELOG and merge!

@mennenia I'd think in that case, we'd want to log/be notified of it, but I think gracefully handling it for the end user is 👌

**Comment by orta** [comment]
ideally the metaphysics schema should tell us if this can be nil ( but we don't [have strict checks on](https://ariya.io/2016/10/typescript-2-and-strict-null-checking) ) so more checking is better (to an extent )

**Comment by orta** [comment]
👍 works for me

**Pull request merged**
