### PR TITLE
[SwitchView] Moves our RN Switch View coordinator to use frame layouts

### PR DESCRIPTION
**Pull request by orta**
Instead of AutoLayout, which was causing conflicts in Artist and Gene pages, but wouldn't allow Gene rotation on iPad.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">The following files do not have tests: <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/components/artwork_grids/artwork.js">lib/components/artwork_grids/artwork.js</a>, <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/components/home/artist_rails/artist_card.js">lib/components/home/artist_rails/artist_card.js</a>, <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/components/home/artist_rails/artist_rail.js">lib/components/home/artist_rails/artist_rail.js</a>, <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/components/home/artwork_rails/artwork_rail_header.js">lib/components/home/artwork_rails/artwork_rail_header.js</a>, <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/components/home/hero_units.js">lib/components/home/hero_units.js</a>, <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/components/home/search_bar.js">lib/components/home/search_bar.js</a>, <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/containers/artist.js">lib/containers/artist.js</a>, <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/containers/home.js">lib/containers/home.js</a> &amp; <a href="https://github.com/artsy/emission/blob/eb08b82e4d878c4e01bbe890f698294495e53625/lib/native_modules/switch_board.js">lib/native_modules/switch_board.js</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by orta** [comment]
aww, this fixes the warnings, but doesn't fix the rotation bug on the gene view 💃

**Comment by alloy** [comment]
Did you verify that this does not break other views, such as the artist view? Because even if it doesn’t fix your original issue, I’ll take getting rid of these warnings _any_ day.

**Comment by orta** [comment]
I did verify that, all is 👍  on Artists ( this is using a local packager )

screen shot 2016-10-19 at 11 33 19

**Comment by alloy** [comment]
Perfect 👍

**Comment by alloy** [comment]
@orta So what’s the final conclusion, shall I merge this? It seems innocuous enough, but those are always famous last words as well.

**Comment by orta** [comment]
savour it IMO, can make sure it's AOK on the next run

**Comment by orta** [comment]
alright, now 3.0 is ou, this is good to go

**Comment by alloy** [comment]
Aye 👍

**Pull request merged**
