### PR TITLE
Fixes CI #trivial

### PR DESCRIPTION
**Pull request by ashfurrow**
#1584 broke CI because it upgraded to Bundler 2.x. For some reason, CI passed. But it's failing on master ([example](https://circleci.com/gh/artsy/emission/1559)). ~This PR sets the env var that _appears_ to tell Circle CI what bundler version to use. It's not well-documented, so fingers-crossed!~ 

The solution required a manual `sudo gem install bundler -v 2.0.1`, which I don't _love_, but I can't argue with the results.

#trivial

### CODE REVIEW

**Comment by ashfurrow** [comment]
Circle CI is happy, though that _could_ be because it's skipped the build altogether. I'll take a closer look later.

**Comment by ashfurrow** [comment]
I've added https://github.com/artsy/emission/pull/1585/commits/2cd2ceeed3203ebea7b27f6625fa4f99705df74a to this PR to trigger a full Circle CI run.

**Comment by ashfurrow** [comment]
Okay, the CI failure from master is fixed in this commit: https://github.com/artsy/emission/pull/1585/commits/f01e417401502eb6be85f0efc7ee4ff398e37490

And the problem where some PRs were having their native unit tests skipped incorrectly is fixed here: https://github.com/artsy/emission/pull/1585/commits/031ed4a06acb93d086cc65a180f10b6bd5e7dd76

I'll update the PR description.

**Comment by alloy** [comment]
Nice 👌 Merge on green

Btw, are those Ruby formatting changes prettier for Ruby? 😃

**Comment by ashfurrow** [comment]
@alloy I believe they are! I added one newline to the `Podfile`, hit "Save", and VSCode spat out those changes. In any case, I like them 👍

**Pull request merged**
