### PR TITLE
ME-21 - Moving chevron

### PR DESCRIPTION
**Pull request by kierangillen**
- https://artsyproduct.atlassian.net/browse/ME-21

## Now:

...nothing happens

#trivial
#skip_new_tests

### CODE REVIEW

**Comment by sweir27** [comment]
Wait wait but why was it moving before? 😮

**Comment by kierangillen** [comment]
@sweir27 Tbh not exactly sure but I think it could be a RN bug with the `Text` element adding whitespace before the SVG, I think probably best to avoid wrapping SVGs with `Text` elements 🤷‍♂

**Comment by kierangillen** [comment]
@sweir27 Actually the margin-left props is the issue, for some reason the `Text` element appears to be rendering it over and over while `onPress` is held down and its `ML` props are being applied `++`

**Comment by sweir27** [comment]
@kierangillen whoa. Good find!!

**Pull request merged**
