### PR TITLE
[WFU] fix bug in artwork rail header

### PR DESCRIPTION
**Pull request by sarahscott**
Fixes https://github.com/artsy/eigen/issues/2302

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Running your Dangerfile has Failed</td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: TypeError

```sh
TypeError: Cannot read property 'length' of null
    at reactComponentForPath (/home/travis/build/artsy/dangerfile.ts:87:12)
    at Array.map (native)
    at Object.<anonymous> (/home/travis/build/artsy/dangerfile.ts:94:52)
    at Runtime._execModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/build/index.js:447:13)
    at Runtime.requireModule (/home/travis/build/artsy/emission/node_modules/jest-runtime/build/index.js:295:14)
    at /home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:92:13
    at ensureCleanDangerfile (/home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:129:3)
    at Object.<anonymous> (/home/travis/build/artsy/emission/node_modules/danger/source/runner/DangerfileRunner.ts:91:3)
    at step (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:32:23)
    at Object.next (/home/travis/build/artsy/emission/node_modules/danger/distribution/runner/DangerfileRunner.js:13:53)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by sarahscott** [comment]
Danger isn't working but all tests are passing

**Comment by mennenia** [comment]
looks good ^_^ 

btw, are the yarn changes intentional?

**Comment by sarahscott** [comment]
hmm no they aren't - they appeared after a `yarn install`. should i check them out?

**Comment by mennenia** [comment]
I would, I think. Just so this change is specifically about the artwork rail.

**Comment by mennenia** [comment]
Awesomee! Mergin'

**Pull request merged**
