### PR TITLE
[Home][ArtworksRail] Fix for layout issues on-device #tiny

### PR DESCRIPTION
**Pull request by sarahscott**
`Dimensions` is less reliable on-device as it is in the sim.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG added.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">The following files do not have tests: <a href="https://github.com/artsy/emission/blob/110f68f0a6c38aa0167a015a07478f5cd027833e/lib/components/artwork_grids/generic_grid.js">lib/components/artwork_grids/generic_grid.js</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mennenia** [comment]
Do we want to change this in more places then? :o @sarahscott

**Comment by sarahscott** [comment]
Probably. We need to have a team discussion about handling screen sizes anyway but I think this PR should be merged as-is and then we can spot other places that need immediate attention after some rigorous QA.

**Comment by mennenia** [comment]
Sure sounds good. 

Just curious (and for future reference) - what was it about `dimensions` that wasn't as robust? Is that documented in React Native documentation? :o

**Comment by sarahscott** [comment]
It doesn't consistently update upon rotation but layout does

**Pull request merged**
